### ISSUE TITLE
Patches system failed error

### ISSUE THREAD

**Issue by andreasaez** [firecore/Seas0nPass#12]
I can't even get through to installing it, I've tried both with 0.97 and 0.96. Just did a clean reinstall of the latest Apple software too, thought I'd start totally clean.

**Comment by mainczjs** [comment]
have the same issue here... also tried 0.95 to 0.97 with no luck.

**Comment by lechium** [comment]
any more background info? if you are on sierra it is untested there, and probably will be for a while. sorry.

**Comment by mainczjs** [comment]
yep, sierra it is. I will try to run it under El Capitan then!

**Comment by Casburggraaf** [comment]
If you download the source and build it manually in xcode(sign with free apple id) it works!

**Comment by gabrielboliveira** [comment]
@Casburggraaf is right! Thanks! I was able to make it work building from source, but didn't need to sign the code, just removed all signing codes.

**Comment by lechium** [comment]
This has been addressed in the latest source, gave a build to firecore and after testing and verifying the release im sure he'll be quick to deploy it.

sorry for the delay on attention on this, didnt have access to any comps running sierra till fairly recently.
