### ISSUE TITLE
Seas0npass can't call home anymore

### ISSUE THREAD

**Issue by firecracker1** [firecore/Seas0nPass#19]
I understand this project is abandoned but it trying to call home before it opens and giving a error message d"Seas0npass is unable to retrieve firmware details"

Can those checks be removed since this is the only atv jailbreak tool that installs SSH plus many other features.

**Comment by lechium** [comment]
@firecracker1 i would post any questions about the project to the forum linked in the README, im definitely not updating the project again, sorry. https://community.firecore.com/c/legacy/seas0npass/11

**Comment by firecracker1** [comment]
Thanks so much for taking the time to respond. The source is online, it’s been since Visual Basic 3.0 since I did any programming but maybe I’ll take a shot at removing the checks. Was this a C++ project?

**Comment by lechium** [comment]
@firecracker1 the macOS version is a mix of c languages, mostly objective-c. but getting it to work on modern mac OS versions is practically impossible. and the windows version is missing some crucial code iirc. i was only responsible for the mac version so thats all i can really comment on. tbh im surprised anyone still cares about this project, the appletv 2 is an underpowered paperweight, with or without a jailbreak. its really not worth the effort in my opinion.

**Comment by firecracker1** [comment]
There’s a mental health patient I help look after who on a good day likes to restore a fresh Ipsw to his Apple TV then jailbreak it then configure kodi. It’s something he feels proud to do. 

I’ve been exploring jailbreaking with redsn0w all day but I can’t get the ssh tunnel to open.

ive heard on an old Mac OS that the Mac version still works so I’m procuring an old MacBook to try that 

It’s good to know the pc version might be missing a bunch of sourcecode. I wonder if modern decompilers still work.

there’s got to be a valid way to still get ssh on an Apple TV 2

thanks for the responses. I will close this issue.

**Comment by lechium** [comment]
@firecracker1 you may also want to investigate if sn0wbreeze still works. im sorry i couldnt be more helpful

**Comment by firecracker1** [comment]
![CFDE9890-EC36-4E44-A0FC-EF04714C6D91](https://user-images.githubusercontent.com/12420209/133180515-0918bbb2-9222-4848-a415-8dd7c0216b5b.jpeg)

sn0wbreeze wouldn’t work since the versions it works with aren’t being signed anymore. iFaith won’t stitch blobs without being able to talk to the iAquas blob verification server.

however I got a 2010 MacBook from goodwill for $25, put a hard drive in it, put high Sierra on it and your Mac version of seas0npass works perfectly. Thank you!

**Comment by lechium** [comment]
@firecracker1 awesome, glad you found a solution
